/**
 * Generated by orval v6.29.0 🍺
 * Do not edit manually.
 * Checklist API
 * API for managing checklists and their items.
 * OpenAPI spec version: 1.0.0
 */
export type UpdateSubItem = {
  checked?: boolean;
  quantity?: number | null;
  text?: string;
};

export type CreateSubItem = {
  quantity?: number | null;
  text?: string;
};

export type SubItem = {
  checked?: boolean;
  quantity?: number | null;
  subItemId?: string;
  text?: string;
};

export type UpdateItem = {
  checked?: boolean;
  isCollapsed?: boolean;
  quantity?: number | null;
  text?: string;
};

export type CreateItemSubItemsItem = {
  quantity?: number | null;
  text?: string;
};

export type CreateItem = {
  quantity?: number | null;
  subItems?: CreateItemSubItemsItem[];
  text?: string;
};

export type Item = {
  checked?: boolean;
  isCollapsed?: boolean;
  itemId?: string;
  position?: number;
  quantity?: number | null;
  subItems?: SubItem[];
  text?: string;
};

export type CreateChecklist = {
  title?: string;
};

export type Checklist = {
  checklistId?: string;
  items?: Item[];
  title?: string;
};

export type GetChecklistsParams = {
  stale?: string;
};
