/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ClaimWorkspaceInviteResponse,
  ErrorResponseResponse
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';


  
  
  
/**
 * @summary Claim a workspace invite
 */
export const claimWorkspaceInvite = (
    token: string,
 ) => {
    return customInstance<ClaimWorkspaceInviteResponse>(
    {url: `/api/v1/workspace-invites/${token}/claim`, method: 'POST'
    },
    );
  }



export const getClaimWorkspaceInviteMutationFetcher = (token: string, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return claimWorkspaceInvite(token);
  }
}
export const getClaimWorkspaceInviteMutationKey = (token: string,) => [`/api/v1/workspace-invites/${token}/claim`] as const;

export type ClaimWorkspaceInviteMutationResult = NonNullable<Awaited<ReturnType<typeof claimWorkspaceInvite>>>
export type ClaimWorkspaceInviteMutationError = ErrorResponseResponse

/**
 * @summary Claim a workspace invite
 */
export const useClaimWorkspaceInvite = <TError = ErrorResponseResponse>(
  token: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof claimWorkspaceInvite>>, TError, Key, Arguments, Awaited<ReturnType<typeof claimWorkspaceInvite>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getClaimWorkspaceInviteMutationKey(token);
  const swrFn = getClaimWorkspaceInviteMutationFetcher(token);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
