openapi: 3.0.3
info:
  title: Checklist API
  description: API for managing checklists and their items.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/api/v1
tags:
  - name: Checklists
    description: Operations related to checklists
  - name: Checklist Items
    description: Operations related to checklist items
  - name: Checklist Sub-Items
    description: Operations related to checklist sub-items
paths:
  /checklists:
    get:
      tags:
        - Checklists
      summary: Get all checklists
      operationId: getChecklists
      responses:
        "200":
          description: A list of checklists
          content:
            application/json:
              schema:
                type: object
                properties:
                  checklists:
                    type: array
                    items:
                      $ref: '#/components/schemas/Checklist'
    post:
      tags:
        - Checklists
      summary: Create a new checklist
      operationId: createChecklist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChecklist'
      responses:
        "201":
          description: The created checklist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checklist'
  /checklists/{checklistId}:
    parameters:
      - name: checklistId
        in: path
        required: true
        schema:
          type: string
    patch:
      tags:
        - Checklists
      summary: Update a checklist's title
      operationId: updateChecklistTitle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        "200":
          description: The updated checklist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checklist'
    delete:
      tags:
        - Checklists
      summary: Delete a checklist
      operationId: deleteChecklist
      responses:
        "204":
          description: Checklist deleted successfully
  /checklists/{checklistId}/items:
    parameters:
      - name: checklistId
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - Checklist Items
      summary: Add an item to a checklist
      operationId: addItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateItem'
      responses:
        "201":
          description: The created checklist item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /checklists/{checklistId}/items/{itemId}:
    parameters:
      - name: checklistId
        in: path
        required: true
        schema:
          type: string
      - name: itemId
        in: path
        required: true
        schema:
          type: string
    patch:
      tags:
        - Checklist Items
      summary: Update a checklist item
      operationId: updateItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateItem'
      responses:
        "200":
          description: The updated checklist item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      tags:
        - Checklist Items
      summary: Delete a checklist item
      operationId: deleteItem
      responses:
        "204":
          description: Item deleted successfully
  /checklists/{checklistId}/items/{itemId}/reorder:
    parameters:
      - name: checklistId
        in: path
        required: true
        schema:
          type: string
      - name: itemId
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
          - Checklist Items
      summary: Reorder an item in a checklist
      operationId: reorderItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPosition:
                  type: integer
      responses:
        "204":
          description: Item reordered successfully
  /checklists/{checklistId}/items/{itemId}/subitems:
    parameters:
      - name: checklistId
        in: path
        required: true
        schema:
          type: string
      - name: itemId
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - Checklist Sub-Items
      summary: Add a sub-item to a checklist item
      operationId: addSubItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubItem'
      responses:
        "201":
          description: The created sub-item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubItem'
  /checklists/{checklistId}/items/{itemId}/subitems/{subItemId}:
    parameters:
      - name: checklistId
        in: path
        required: true
        schema:
          type: string
      - name: itemId
        in: path
        required: true
        schema:
          type: string
      - name: subItemId
        in: path
        required: true
        schema:
          type: string
    patch:
      tags:
        - Checklist Sub-Items
      summary: Update a sub-item
      operationId: updateSubItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubItem'
      responses:
        "200":
          description: The updated sub-item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubItem'
    delete:
      tags:
        - Checklist Sub-Items
      summary: Delete a sub-item
      operationId: deleteSubItem
      responses:
        "204":
          description: Sub-item deleted successfully
components:
  schemas:
    Checklist:
      type: object
      properties:
        checklistId:
          type: string
        title:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    CreateChecklist:
      type: object
      properties:
        title:
          type: string
    Item:
      type: object
      properties:
        itemId:
          type: string
        text:
          type: string
        quantity:
          type: integer
          nullable: true
        checked:
          type: boolean
        isCollapsed:
          type: boolean
        position:
          type: integer
        subItems:
          type: array
          items:
            $ref: '#/components/schemas/SubItem'
    CreateItem:
      type: object
      properties:
        text:
          type: string
        quantity:
          type: integer
          nullable: true
        subItems:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
              quantity:
                type: integer
                nullable: true
    UpdateItem:
      type: object
      properties:
        text:
          type: string
        quantity:
          type: integer
          nullable: true
        checked:
          type: boolean
        isCollapsed:
          type: boolean
    SubItem:
      type: object
      properties:
        subItemId:
          type: string
        text:
          type: string
        quantity:
          type: integer
          nullable: true
        checked:
          type: boolean
    CreateSubItem:
      type: object
      properties:
        text:
          type: string
        quantity:
          type: integer
          nullable: true
    UpdateSubItem:
      type: object
      properties:
        text:
          type: string
        quantity:
          type: integer
          nullable: true
        checked:
          type: boolean
