/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { ClaimInviteResponse, Error } from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';

/**
 * @summary Claim an invite to gain access to a checklist
 */
export const claimInvite = (token: string) => {
  return customInstance<ClaimInviteResponse>({
    url: `/api/v1/invites/${token}/claim`,
    method: 'POST',
  });
};

export const getClaimInviteMutationFetcher = (token: string) => {
  return (_: Key, __: { arg: Arguments }) => {
    return claimInvite(token);
  };
};
export const getClaimInviteMutationKey = (token: string) =>
  [`/api/v1/invites/${token}/claim`] as const;

export type ClaimInviteMutationResult = NonNullable<Awaited<ReturnType<typeof claimInvite>>>;
export type ClaimInviteMutationError = Error | Error | Error | Error;

/**
 * @summary Claim an invite to gain access to a checklist
 */
export const useClaimInvite = <TError = Error | Error | Error | Error>(
  token: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof claimInvite>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof claimInvite>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getClaimInviteMutationKey(token);
  const swrFn = getClaimInviteMutationFetcher(token);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
