/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ClientIdResponse,
  Error
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';


  
  
  
/**
 * Generates a secure, server-validated client ID for SSE connections. The client ID is tied to the authenticated user and expires after 24 hours.
 * @summary Generate server-side client ID
 */
export const generateClientId = (
    
 ) => {
    return customInstance<ClientIdResponse>(
    {url: `/api/v1/session/client-id`, method: 'POST'
    },
    );
  }



export const getGenerateClientIdMutationFetcher = ( ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return generateClientId();
  }
}
export const getGenerateClientIdMutationKey = () => [`/api/v1/session/client-id`] as const;

export type GenerateClientIdMutationResult = NonNullable<Awaited<ReturnType<typeof generateClientId>>>
export type GenerateClientIdMutationError = Error | Error

/**
 * @summary Generate server-side client ID
 */
export const useGenerateClientId = <TError = Error | Error>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof generateClientId>>, TError, Key, Arguments, Awaited<ReturnType<typeof generateClientId>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getGenerateClientIdMutationKey();
  const swrFn = getGenerateClientIdMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
