/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  DeleteAccount200,
  DeleteAccountParams,
  Error,
  UserDataExport
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';


  
  
  
/**
 * Permanently delete your account and all associated data (checklists, items, shares). This action is irreversible and implements GDPR Article 17 (Right to Erasure).
 * @summary Delete user account (GDPR Right to Erasure)
 */
export const deleteAccount = (
    params: DeleteAccountParams,
 ) => {
    return customInstance<DeleteAccount200>(
    {url: `/api/v1/user/account`, method: 'DELETE',
        params
    },
    );
  }



export const getDeleteAccountMutationFetcher = (params: DeleteAccountParams, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteAccount(params);
  }
}
export const getDeleteAccountMutationKey = (params: DeleteAccountParams,) => [`/api/v1/user/account`, ...(params ? [params]: [])] as const;

export type DeleteAccountMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAccount>>>
export type DeleteAccountMutationError = Error | Error | Error

/**
 * @summary Delete user account (GDPR Right to Erasure)
 */
export const useDeleteAccount = <TError = Error | Error | Error>(
  params: DeleteAccountParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteAccount>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteAccount>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteAccountMutationKey(params);
  const swrFn = getDeleteAccountMutationFetcher(params);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Download all your data in machine-readable JSON format. Implements GDPR Article 20 (Right to Data Portability).
 * @summary Export user data (GDPR Data Portability)
 */
export const exportUserData = (
    
 ) => {
    return customInstance<UserDataExport>(
    {url: `/api/v1/user/data-export`, method: 'GET'
    },
    );
  }



export const getExportUserDataKey = () => [`/api/v1/user/data-export`] as const;

export type ExportUserDataQueryResult = NonNullable<Awaited<ReturnType<typeof exportUserData>>>
export type ExportUserDataQueryError = Error | Error

/**
 * @summary Export user data (GDPR Data Portability)
 */
export const useExportUserData = <TError = Error | Error>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof exportUserData>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getExportUserDataKey() : null);
  const swrFn = () => exportUserData()

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
