/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ChecklistResponse,
  CreateChecklistRequest,
  Error
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';


  
  
  
/**
 * @summary Get all checklists
 */
export const getAllChecklists = (
    
 ) => {
    return customInstance<ChecklistResponse[]>(
    {url: `/api/v1/checklists`, method: 'GET'
    },
    );
  }



export const getGetAllChecklistsKey = () => [`/api/v1/checklists`] as const;

export type GetAllChecklistsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllChecklists>>>
export type GetAllChecklistsQueryError = Error | Error

/**
 * @summary Get all checklists
 */
export const useGetAllChecklists = <TError = Error | Error>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllChecklists>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllChecklistsKey() : null);
  const swrFn = () => getAllChecklists()

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a new checklist
 */
export const createChecklist = (
    createChecklistRequest: CreateChecklistRequest,
 ) => {
    return customInstance<ChecklistResponse>(
    {url: `/api/v1/checklists`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createChecklistRequest
    },
    );
  }



export const getCreateChecklistMutationFetcher = ( ) => {
  return (_: Key, { arg }: { arg: CreateChecklistRequest }) => {
    return createChecklist(arg);
  }
}
export const getCreateChecklistMutationKey = () => [`/api/v1/checklists`] as const;

export type CreateChecklistMutationResult = NonNullable<Awaited<ReturnType<typeof createChecklist>>>
export type CreateChecklistMutationError = Error | Error

/**
 * @summary Create a new checklist
 */
export const useCreateChecklist = <TError = Error | Error>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createChecklist>>, TError, Key, CreateChecklistRequest, Awaited<ReturnType<typeof createChecklist>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateChecklistMutationKey();
  const swrFn = getCreateChecklistMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get checklist by ID
 */
export const getChecklistById = (
    checklistId: number,
 ) => {
    return customInstance<ChecklistResponse>(
    {url: `/api/v1/checklists/${checklistId}`, method: 'GET'
    },
    );
  }



export const getGetChecklistByIdKey = (checklistId: number,) => [`/api/v1/checklists/${checklistId}`] as const;

export type GetChecklistByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getChecklistById>>>
export type GetChecklistByIdQueryError = Error | Error | Error

/**
 * @summary Get checklist by ID
 */
export const useGetChecklistById = <TError = Error | Error | Error>(
  checklistId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getChecklistById>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(checklistId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetChecklistByIdKey(checklistId) : null);
  const swrFn = () => getChecklistById(checklistId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update checklist by ID
 */
export const updateChecklistById = (
    checklistId: number,
    createChecklistRequest: CreateChecklistRequest,
 ) => {
    return customInstance<ChecklistResponse>(
    {url: `/api/v1/checklists/${checklistId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createChecklistRequest
    },
    );
  }



export const getUpdateChecklistByIdMutationFetcher = (checklistId: number, ) => {
  return (_: Key, { arg }: { arg: CreateChecklistRequest }) => {
    return updateChecklistById(checklistId, arg);
  }
}
export const getUpdateChecklistByIdMutationKey = (checklistId: number,) => [`/api/v1/checklists/${checklistId}`] as const;

export type UpdateChecklistByIdMutationResult = NonNullable<Awaited<ReturnType<typeof updateChecklistById>>>
export type UpdateChecklistByIdMutationError = Error | Error | Error

/**
 * @summary Update checklist by ID
 */
export const useUpdateChecklistById = <TError = Error | Error | Error>(
  checklistId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateChecklistById>>, TError, Key, CreateChecklistRequest, Awaited<ReturnType<typeof updateChecklistById>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateChecklistByIdMutationKey(checklistId);
  const swrFn = getUpdateChecklistByIdMutationFetcher(checklistId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete checklist by ID
 */
export const deleteChecklistById = (
    checklistId: number,
 ) => {
    return customInstance<ChecklistResponse>(
    {url: `/api/v1/checklists/${checklistId}`, method: 'DELETE'
    },
    );
  }



export const getDeleteChecklistByIdMutationFetcher = (checklistId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteChecklistById(checklistId);
  }
}
export const getDeleteChecklistByIdMutationKey = (checklistId: number,) => [`/api/v1/checklists/${checklistId}`] as const;

export type DeleteChecklistByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChecklistById>>>
export type DeleteChecklistByIdMutationError = Error | Error

/**
 * @summary Delete checklist by ID
 */
export const useDeleteChecklistById = <TError = Error | Error>(
  checklistId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteChecklistById>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteChecklistById>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteChecklistByIdMutationKey(checklistId);
  const swrFn = getDeleteChecklistByIdMutationFetcher(checklistId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
