/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
export interface Error {
  /**
   * @minLength 0
   */
  message: string;
}

export interface CreateChecklistItemRequest {
  /**
   * Checklist item name (1-500 characters)
   * @minLength 1
   * @maxLength 500
   */
  name: string;
  /**
   * Checklist item rows (max 100 rows per item)
   * @maxItems 100
   */
  rows?: CreateOrUpdateChecklistItemRowRequest[];
}

export type UpdateChecklistItemRequestRowsItem = {
  /**
   * @minimum 1
   */
  id: number;
  /**
   * Row name (1-500 characters)
   * @minLength 1
   * @maxLength 500
   */
  name: string;
  /** @nullable */
  completed: boolean | null;
};

export interface UpdateChecklistItemRequest {
  /**
   * @minimum 1
   */
  id: number;
  /**
   * Checklist item name (1-500 characters)
   * @minLength 1
   * @maxLength 500
   */
  name: string;
  /** */
  completed: boolean;
  /**
   * Checklist item rows (max 100 rows per item)
   * @maxItems 100
   */
  rows: UpdateChecklistItemRequestRowsItem[];
}

export interface ChecklistItemResponse {
  /**
   * @minimum 1
   */
  id: number;
  /**
   * @minLength 1
   */
  name: string;
  /** */
  completed: boolean;
  /**
   * @minimum 1
   */
  orderNumber: number;
  rows: ChecklistItemRowResponse[];
}

export interface ChecklistItemRowResponse {
  /**
   * @minimum 0
   */
  id: number;
  /**
   * @minLength 1
   */
  name: string;
  /** @nullable */
  completed: boolean | null;
}

export interface CreateOrUpdateChecklistItemRowRequest {
  /**
   * Row name (1-500 characters)
   * @minLength 1
   * @maxLength 500
   */
  name: string;
  /** @nullable */
  completed: boolean | null;
}

export type CreateChecklistItemRowRequest = CreateOrUpdateChecklistItemRowRequest;

export interface ChecklistUpdateAndCreateRequest {
  /**
   * Checklist name (1-200 characters)
   * @minLength 1
   * @maxLength 200
   */
  name: string;
}

export type CreateChecklistRequest = ChecklistUpdateAndCreateRequest;

export type UpdateChecklistRequest = ChecklistUpdateAndCreateRequest;

export interface GetChecklistsWithStatsResponse {
  checklists: ChecklistWithStats[];
}

/**
 * Statistics about checklist items
 */
export type ChecklistWithStatsStats = {
  /**
   * Total number of items in the checklist
   * @minimum 0
   */
  totalItems: number;
  /**
   * Number of completed items
   * @minimum 0
   */
  completedItems: number;
};

export interface ChecklistWithStats {
  /**
   * @minimum 1
   */
  id: number;
  /**
   * @minLength 1
   */
  name: string;
  /**
   * Is current user owner of the checklist
   */
  isOwner: boolean;
  /**
   * Whether this checklist is shared with others (only true for owners)
   */
  isShared: boolean;
  /**
   * Number of users this checklist is shared with (only included for owners)
   */
  numberOfSharedUsers?: number;
  /** Statistics about checklist items */
  stats: ChecklistWithStatsStats;
}

/**
 * Statistics about checklist items
 */
export type ChecklistResponseStats = {
  /**
   * Total number of items in the checklist
   * @minimum 0
   */
  totalItems: number;
  /**
   * Number of completed items
   * @minimum 0
   */
  completedItems: number;
};

export interface ChecklistResponse {
  /**
   * @minimum 1
   */
  id: number;
  /**
   * @minLength 1
   */
  name: string;
  /**
   * User ID of the checklist owner
   */
  owner: string;
  /**
   * Whether the current user is the owner
   */
  isOwner: boolean;
  /**
   * Whether this checklist is shared with others (only true for owners)
   */
  isShared: boolean;
  /** List of user IDs this checklist is shared with (only included for owners) */
  sharedWith?: string[];
  /** Statistics about checklist items */
  stats: ChecklistResponseStats;
  /** Full list of items (only included in detail view) */
  items?: ChecklistItemResponse[];
}

/**
 * Event type identifier
 */
export type EventEnvelopeType = (typeof EventEnvelopeType)[keyof typeof EventEnvelopeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventEnvelopeType = {
  checklistItemCreated: 'checklistItemCreated',
  checklistItemUpdated: 'checklistItemUpdated',
  checklistItemDeleted: 'checklistItemDeleted',
  checklistItemRowAdded: 'checklistItemRowAdded',
  checklistItemRowUpdated: 'checklistItemRowUpdated',
  checklistItemRowDeleted: 'checklistItemRowDeleted',
  checklistItemReordered: 'checklistItemReordered',
} as const;

/**
 * Payload structure depends on event type:
  - checklistItemCreated, checklistItemUpdated: ChecklistItemResponse
  - checklistItemDeleted: ChecklistItemDeletedEventPayload
  - checklistItemRowAdded, checklistItemRowUpdated: ChecklistItemRowResponse
  - checklistItemRowDeleted: ChecklistItemRowDeletedEventPayload
  - checklistItemReordered: ChecklistItemReorderedEventPayload

 */
export type EventEnvelopePayload =
  | ChecklistItemResponse
  | ChecklistItemRowResponse
  | ChecklistItemRowDeletedEventPayload
  | ChecklistItemRowAddedEventPayload
  | ChecklistItemDeletedEventPayload
  | ChecklistItemReorderedEventPayload;

/**
 * Envelope for SSE events; sent as JSON in the SSE data field.
The `type` field indicates the event type, and the `payload` field contains the event data.
The expected structure of `payload` for each `type` is as follows:
  - checklistItemCreated: ChecklistItemResponse
  - checklistItemUpdated: ChecklistItemResponse
  - checklistItemDeleted: ChecklistItemDeletedEventPayload
  - checklistItemRowAdded: ChecklistItemRowResponse
  - checklistItemRowUpdated: ChecklistItemRowResponse
  - checklistItemRowDeleted: ChecklistItemRowDeletedEventPayload
  - checklistItemRowAdded: ChecklistItemRowAddedEventPayload
  - checklistItemReordered: ChecklistItemReorderedEventPayload
For event types not listed above, `payload` may be null or a free-form object.

 */
export interface EventEnvelope {
  /** Event type identifier */
  type: EventEnvelopeType;
  /** Payload structure depends on event type:
  - checklistItemCreated, checklistItemUpdated: ChecklistItemResponse
  - checklistItemDeleted: ChecklistItemDeletedEventPayload
  - checklistItemRowAdded, checklistItemRowUpdated: ChecklistItemRowResponse
  - checklistItemRowDeleted: ChecklistItemRowDeletedEventPayload
  - checklistItemReordered: ChecklistItemReorderedEventPayload
 */
  payload?: EventEnvelopePayload;
}

export interface ChecklistItemRowDeletedEventPayload {
  /**
   * @minimum 1
   */
  itemId: number;
  /**
   * @minimum 1
   */
  rowId: number;
}

export interface ChecklistItemRowAddedEventPayload {
  /**
   * @minimum 1
   */
  itemId: number;
  row: ChecklistItemRowResponse;
}

export interface ChecklistItemDeletedEventPayload {
  /**
   * @minimum 1
   */
  itemId: number;
}

export interface ChecklistItemReorderedEventPayload {
  /**
   * @minimum 1
   */
  itemId: number;
  /**
   * @minimum 1
   */
  newOrderNumber: number;
  /** Indicates if the order number was changed */
  orderChanged: boolean;
}

export interface CreateInviteRequest {
  /**
   * Optional friendly name for the invite (e.g., "For John", "Team members")
   * @maxLength 100
   * @nullable
   */
  name?: string | null;
  /**
   * Hours until invite expires (null = never expires)
   * @minimum 1
   * @maximum 8760
   * @nullable
   */
  expiresInHours?: number | null;
  /**
   * If true, invite can only be claimed once
   */
  isSingleUse: boolean;
}

export interface InviteResponse {
  /** @minimum 1 */
  id: number;
  /** @minimum 1 */
  checklistId: number;
  /**
   * Optional friendly name for the invite
   * @nullable
   */
  name?: string | null;
  /**
   * @minLength 64
   * @maxLength 64
   */
  inviteToken: string;
  /** Full URL for sharing */
  inviteUrl: string;
  createdAt: string;
  /** @nullable */
  expiresAt?: string | null;
  /**
   * User ID who claimed (for backend use only, don't display)
   * @nullable
   */
  claimedBy?: string | null;
  /** @nullable */
  claimedAt?: string | null;
  isSingleUse: boolean;
  /** Computed field indicating if invite is expired */
  isExpired: boolean;
  /** Computed field indicating if invite is claimed */
  isClaimed: boolean;
}

export interface ClaimInviteResponse {
  /** @minimum 1 */
  checklistId: number;
  message?: string;
}

export type UserDataExportChecklistsItemItemsItemRowsItem = {
  id?: number;
  name?: string;
  completed?: boolean;
};

export type UserDataExportChecklistsItemItemsItem = {
  id?: number;
  name?: string;
  completed?: boolean;
  orderNumber?: number;
  rows?: UserDataExportChecklistsItemItemsItemRowsItem[];
};

export type UserDataExportChecklistsItemSharesItem = {
  sharedWithUserId?: string;
  permissionLevel?: string;
  sharedAt?: string;
};

export type UserDataExportChecklistsItem = {
  id?: number;
  name?: string;
  createdAt?: string;
  items?: UserDataExportChecklistsItemItemsItem[];
  /** Users with whom this checklist is shared */
  shares?: UserDataExportChecklistsItemSharesItem[];
};

/**
 * Complete export of user data for GDPR compliance
 */
export interface UserDataExport {
  /** Google User ID (anonymous identifier) */
  userId: string;
  /** Timestamp of data export */
  exportedAt: string;
  checklists: UserDataExportChecklistsItem[];
}

/**
 * Response containing a server-generated client ID
 */
export interface ClientIdResponse {
  /** Secure, server-validated client ID for SSE connections */
  clientId: string;
}

/**
 * A list of checklist items with statistics
 */
export type GetChecklistsWithStatsResponseResponse = GetChecklistsWithStatsResponse;

/**
 * Error response
 */
export type ErrorResponseResponse = Error;

/**
 * Client identifier sent by frontend in headers
 */
export type XClientIdParameter = string;

export type Get200 = {
  status?: string;
};

export type GetAllChecklistItemsParams = {
  /**
   * Sort order
   */
  sort?: GetAllChecklistItemsSort;
  /**
   * Filter by completed status
   */
  completed?: boolean;
};

export type GetAllChecklistItemsSort =
  (typeof GetAllChecklistItemsSort)[keyof typeof GetAllChecklistItemsSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAllChecklistItemsSort = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ToggleChecklistItemCompleteBody = {
  /** New completion status */
  completed: boolean;
};

export type ChangeChecklistItemOrderNumberParams = {
  sortOrder?: ChangeChecklistItemOrderNumberSortOrder;
};

export type ChangeChecklistItemOrderNumberSortOrder =
  (typeof ChangeChecklistItemOrderNumberSortOrder)[keyof typeof ChangeChecklistItemOrderNumberSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeChecklistItemOrderNumberSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ChangeChecklistItemOrderNumberBody = {
  /**
   * New order number (1-10000)
   * @minimum 1
   * @maximum 10000
   */
  newOrderNumber: number;
};

export type ChangeChecklistItemOrderNumber200 = {
  /** @minimum 1 */
  oldOrderNumber?: number;
  /** @minimum 1 */
  newOrderNumber?: number;
};

export type GetEventsStreamForChecklistItemsParams = {
  /**
   * Client identifier passed by frontend
   */
  clientId?: string;
};

export type DeleteAccountParams = {
  /**
   * Must be set to 'true' to confirm deletion
   */
  confirm: boolean;
};

export type DeleteAccount200 = {
  message?: string;
};
