/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ChecklistItemResponse,
  ClaimTemplateInviteResponse,
  CreateInviteRequest,
  CreateTemplateFromItemRequest,
  CreateTemplateRequest,
  Error,
  TemplateInviteResponse,
  TemplateResponse
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';


  
  
  
/**
 * @summary List all templates
 */
export const getAllTemplates = (
    
 ) => {
    return customInstance<TemplateResponse[]>(
    {url: `/api/v1/templates`, method: 'GET'
    },
    );
  }



export const getGetAllTemplatesKey = () => [`/api/v1/templates`] as const;

export type GetAllTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTemplates>>>
export type GetAllTemplatesQueryError = Error

/**
 * @summary List all templates
 */
export const useGetAllTemplates = <TError = Error>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllTemplates>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllTemplatesKey() : null);
  const swrFn = () => getAllTemplates()

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a new template
 */
export const createTemplate = (
    createTemplateRequest: CreateTemplateRequest,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateRequest
    },
    );
  }



export const getCreateTemplateMutationFetcher = ( ) => {
  return (_: Key, { arg }: { arg: CreateTemplateRequest }) => {
    return createTemplate(arg);
  }
}
export const getCreateTemplateMutationKey = () => [`/api/v1/templates`] as const;

export type CreateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createTemplate>>>
export type CreateTemplateMutationError = Error

/**
 * @summary Create a new template
 */
export const useCreateTemplate = <TError = Error>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTemplate>>, TError, Key, CreateTemplateRequest, Awaited<ReturnType<typeof createTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTemplateMutationKey();
  const swrFn = getCreateTemplateMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create template from existing checklist item
 */
export const createTemplateFromItem = (
    createTemplateFromItemRequest: CreateTemplateFromItemRequest,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates/from-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateFromItemRequest
    },
    );
  }



export const getCreateTemplateFromItemMutationFetcher = ( ) => {
  return (_: Key, { arg }: { arg: CreateTemplateFromItemRequest }) => {
    return createTemplateFromItem(arg);
  }
}
export const getCreateTemplateFromItemMutationKey = () => [`/api/v1/templates/from-items`] as const;

export type CreateTemplateFromItemMutationResult = NonNullable<Awaited<ReturnType<typeof createTemplateFromItem>>>
export type CreateTemplateFromItemMutationError = Error

/**
 * @summary Create template from existing checklist item
 */
export const useCreateTemplateFromItem = <TError = Error>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTemplateFromItem>>, TError, Key, CreateTemplateFromItemRequest, Awaited<ReturnType<typeof createTemplateFromItem>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTemplateFromItemMutationKey();
  const swrFn = getCreateTemplateFromItemMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get template by ID
 */
export const getTemplateById = (
    templateId: number,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates/${templateId}`, method: 'GET'
    },
    );
  }



export const getGetTemplateByIdKey = (templateId: number,) => [`/api/v1/templates/${templateId}`] as const;

export type GetTemplateByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplateById>>>
export type GetTemplateByIdQueryError = Error

/**
 * @summary Get template by ID
 */
export const useGetTemplateById = <TError = Error>(
  templateId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTemplateById>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(templateId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTemplateByIdKey(templateId) : null);
  const swrFn = () => getTemplateById(templateId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update template
 */
export const updateTemplate = (
    templateId: number,
    createTemplateRequest: CreateTemplateRequest,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates/${templateId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateRequest
    },
    );
  }



export const getUpdateTemplateMutationFetcher = (templateId: number, ) => {
  return (_: Key, { arg }: { arg: CreateTemplateRequest }) => {
    return updateTemplate(templateId, arg);
  }
}
export const getUpdateTemplateMutationKey = (templateId: number,) => [`/api/v1/templates/${templateId}`] as const;

export type UpdateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateTemplate>>>
export type UpdateTemplateMutationError = Error

/**
 * @summary Update template
 */
export const useUpdateTemplate = <TError = Error>(
  templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateTemplate>>, TError, Key, CreateTemplateRequest, Awaited<ReturnType<typeof updateTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateTemplateMutationKey(templateId);
  const swrFn = getUpdateTemplateMutationFetcher(templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete template
 */
export const deleteTemplate = (
    templateId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/templates/${templateId}`, method: 'DELETE'
    },
    );
  }



export const getDeleteTemplateMutationFetcher = (templateId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteTemplate(templateId);
  }
}
export const getDeleteTemplateMutationKey = (templateId: number,) => [`/api/v1/templates/${templateId}`] as const;

export type DeleteTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTemplate>>>
export type DeleteTemplateMutationError = Error

/**
 * @summary Delete template
 */
export const useDeleteTemplate = <TError = Error>(
  templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteTemplate>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteTemplateMutationKey(templateId);
  const swrFn = getDeleteTemplateMutationFetcher(templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Apply template to checklist (creates one checklist item with rows)
 */
export const applyTemplate = (
    checklistId: number,
    templateId: number,
 ) => {
    return customInstance<ChecklistItemResponse>(
    {url: `/api/v1/checklists/${checklistId}/apply-template/${templateId}`, method: 'POST'
    },
    );
  }



export const getApplyTemplateMutationFetcher = (checklistId: number,
    templateId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return applyTemplate(checklistId, templateId);
  }
}
export const getApplyTemplateMutationKey = (checklistId: number,
    templateId: number,) => [`/api/v1/checklists/${checklistId}/apply-template/${templateId}`] as const;

export type ApplyTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof applyTemplate>>>
export type ApplyTemplateMutationError = Error

/**
 * @summary Apply template to checklist (creates one checklist item with rows)
 */
export const useApplyTemplate = <TError = Error>(
  checklistId: number,
    templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof applyTemplate>>, TError, Key, Arguments, Awaited<ReturnType<typeof applyTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getApplyTemplateMutationKey(checklistId,templateId);
  const swrFn = getApplyTemplateMutationFetcher(checklistId,templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary List active invite links for a template
 */
export const getTemplateInvites = (
    templateId: number,
 ) => {
    return customInstance<TemplateInviteResponse[]>(
    {url: `/api/v1/templates/${templateId}/invites`, method: 'GET'
    },
    );
  }



export const getGetTemplateInvitesKey = (templateId: number,) => [`/api/v1/templates/${templateId}/invites`] as const;

export type GetTemplateInvitesQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplateInvites>>>
export type GetTemplateInvitesQueryError = Error

/**
 * @summary List active invite links for a template
 */
export const useGetTemplateInvites = <TError = Error>(
  templateId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTemplateInvites>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(templateId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTemplateInvitesKey(templateId) : null);
  const swrFn = () => getTemplateInvites(templateId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a new invite link for a template
 */
export const createTemplateInvite = (
    templateId: number,
    createInviteRequest: CreateInviteRequest,
 ) => {
    return customInstance<TemplateInviteResponse>(
    {url: `/api/v1/templates/${templateId}/invites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInviteRequest
    },
    );
  }



export const getCreateTemplateInviteMutationFetcher = (templateId: number, ) => {
  return (_: Key, { arg }: { arg: CreateInviteRequest }) => {
    return createTemplateInvite(templateId, arg);
  }
}
export const getCreateTemplateInviteMutationKey = (templateId: number,) => [`/api/v1/templates/${templateId}/invites`] as const;

export type CreateTemplateInviteMutationResult = NonNullable<Awaited<ReturnType<typeof createTemplateInvite>>>
export type CreateTemplateInviteMutationError = Error

/**
 * @summary Create a new invite link for a template
 */
export const useCreateTemplateInvite = <TError = Error>(
  templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTemplateInvite>>, TError, Key, CreateInviteRequest, Awaited<ReturnType<typeof createTemplateInvite>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTemplateInviteMutationKey(templateId);
  const swrFn = getCreateTemplateInviteMutationFetcher(templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Revoke a template invite link
 */
export const revokeTemplateInvite = (
    inviteId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/templates/invites/${inviteId}`, method: 'DELETE'
    },
    );
  }



export const getRevokeTemplateInviteMutationFetcher = (inviteId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return revokeTemplateInvite(inviteId);
  }
}
export const getRevokeTemplateInviteMutationKey = (inviteId: number,) => [`/api/v1/templates/invites/${inviteId}`] as const;

export type RevokeTemplateInviteMutationResult = NonNullable<Awaited<ReturnType<typeof revokeTemplateInvite>>>
export type RevokeTemplateInviteMutationError = Error

/**
 * @summary Revoke a template invite link
 */
export const useRevokeTemplateInvite = <TError = Error>(
  inviteId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof revokeTemplateInvite>>, TError, Key, Arguments, Awaited<ReturnType<typeof revokeTemplateInvite>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRevokeTemplateInviteMutationKey(inviteId);
  const swrFn = getRevokeTemplateInviteMutationFetcher(inviteId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Claim a template invite to gain access to a template
 */
export const claimTemplateInvite = (
    token: string,
 ) => {
    return customInstance<ClaimTemplateInviteResponse>(
    {url: `/api/v1/template-invites/${token}/claim`, method: 'POST'
    },
    );
  }



export const getClaimTemplateInviteMutationFetcher = (token: string, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return claimTemplateInvite(token);
  }
}
export const getClaimTemplateInviteMutationKey = (token: string,) => [`/api/v1/template-invites/${token}/claim`] as const;

export type ClaimTemplateInviteMutationResult = NonNullable<Awaited<ReturnType<typeof claimTemplateInvite>>>
export type ClaimTemplateInviteMutationError = Error

/**
 * @summary Claim a template invite to gain access to a template
 */
export const useClaimTemplateInvite = <TError = Error>(
  token: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof claimTemplateInvite>>, TError, Key, Arguments, Awaited<ReturnType<typeof claimTemplateInvite>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getClaimTemplateInviteMutationKey(token);
  const swrFn = getClaimTemplateInviteMutationFetcher(token);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Remove yourself from a shared template. Owners cannot leave their own templates.
 * @summary Leave a shared template
 */
export const leaveSharedTemplate = (
    templateId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/templates/${templateId}/leave`, method: 'POST'
    },
    );
  }



export const getLeaveSharedTemplateMutationFetcher = (templateId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return leaveSharedTemplate(templateId);
  }
}
export const getLeaveSharedTemplateMutationKey = (templateId: number,) => [`/api/v1/templates/${templateId}/leave`] as const;

export type LeaveSharedTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof leaveSharedTemplate>>>
export type LeaveSharedTemplateMutationError = Error

/**
 * @summary Leave a shared template
 */
export const useLeaveSharedTemplate = <TError = Error>(
  templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof leaveSharedTemplate>>, TError, Key, Arguments, Awaited<ReturnType<typeof leaveSharedTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getLeaveSharedTemplateMutationKey(templateId);
  const swrFn = getLeaveSharedTemplateMutationFetcher(templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
