/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AssignTemplateToWorkspaceRequest,
  ChecklistItemResponse,
  CreateTemplateFromItemRequest,
  CreateTemplateRequest,
  Error,
  ErrorResponseResponse,
  TemplateResponse
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';


  
  
  
/**
 * @summary List all templates
 */
export const getAllTemplates = (
    
 ) => {
    return customInstance<TemplateResponse[]>(
    {url: `/api/v1/templates`, method: 'GET'
    },
    );
  }



export const getGetAllTemplatesKey = () => [`/api/v1/templates`] as const;

export type GetAllTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTemplates>>>
export type GetAllTemplatesQueryError = Error

/**
 * @summary List all templates
 */
export const useGetAllTemplates = <TError = Error>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllTemplates>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllTemplatesKey() : null);
  const swrFn = () => getAllTemplates()

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a new template
 */
export const createTemplate = (
    createTemplateRequest: CreateTemplateRequest,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateRequest
    },
    );
  }



export const getCreateTemplateMutationFetcher = ( ) => {
  return (_: Key, { arg }: { arg: CreateTemplateRequest }) => {
    return createTemplate(arg);
  }
}
export const getCreateTemplateMutationKey = () => [`/api/v1/templates`] as const;

export type CreateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createTemplate>>>
export type CreateTemplateMutationError = Error

/**
 * @summary Create a new template
 */
export const useCreateTemplate = <TError = Error>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTemplate>>, TError, Key, CreateTemplateRequest, Awaited<ReturnType<typeof createTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTemplateMutationKey();
  const swrFn = getCreateTemplateMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create template from existing checklist item
 */
export const createTemplateFromItem = (
    createTemplateFromItemRequest: CreateTemplateFromItemRequest,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates/from-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateFromItemRequest
    },
    );
  }



export const getCreateTemplateFromItemMutationFetcher = ( ) => {
  return (_: Key, { arg }: { arg: CreateTemplateFromItemRequest }) => {
    return createTemplateFromItem(arg);
  }
}
export const getCreateTemplateFromItemMutationKey = () => [`/api/v1/templates/from-items`] as const;

export type CreateTemplateFromItemMutationResult = NonNullable<Awaited<ReturnType<typeof createTemplateFromItem>>>
export type CreateTemplateFromItemMutationError = Error

/**
 * @summary Create template from existing checklist item
 */
export const useCreateTemplateFromItem = <TError = Error>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createTemplateFromItem>>, TError, Key, CreateTemplateFromItemRequest, Awaited<ReturnType<typeof createTemplateFromItem>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateTemplateFromItemMutationKey();
  const swrFn = getCreateTemplateFromItemMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get template by ID
 */
export const getTemplateById = (
    templateId: number,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates/${templateId}`, method: 'GET'
    },
    );
  }



export const getGetTemplateByIdKey = (templateId: number,) => [`/api/v1/templates/${templateId}`] as const;

export type GetTemplateByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplateById>>>
export type GetTemplateByIdQueryError = Error

/**
 * @summary Get template by ID
 */
export const useGetTemplateById = <TError = Error>(
  templateId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTemplateById>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(templateId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTemplateByIdKey(templateId) : null);
  const swrFn = () => getTemplateById(templateId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update template
 */
export const updateTemplate = (
    templateId: number,
    createTemplateRequest: CreateTemplateRequest,
 ) => {
    return customInstance<TemplateResponse>(
    {url: `/api/v1/templates/${templateId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateRequest
    },
    );
  }



export const getUpdateTemplateMutationFetcher = (templateId: number, ) => {
  return (_: Key, { arg }: { arg: CreateTemplateRequest }) => {
    return updateTemplate(templateId, arg);
  }
}
export const getUpdateTemplateMutationKey = (templateId: number,) => [`/api/v1/templates/${templateId}`] as const;

export type UpdateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateTemplate>>>
export type UpdateTemplateMutationError = Error

/**
 * @summary Update template
 */
export const useUpdateTemplate = <TError = Error>(
  templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateTemplate>>, TError, Key, CreateTemplateRequest, Awaited<ReturnType<typeof updateTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateTemplateMutationKey(templateId);
  const swrFn = getUpdateTemplateMutationFetcher(templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete template
 */
export const deleteTemplate = (
    templateId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/templates/${templateId}`, method: 'DELETE'
    },
    );
  }



export const getDeleteTemplateMutationFetcher = (templateId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteTemplate(templateId);
  }
}
export const getDeleteTemplateMutationKey = (templateId: number,) => [`/api/v1/templates/${templateId}`] as const;

export type DeleteTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTemplate>>>
export type DeleteTemplateMutationError = Error

/**
 * @summary Delete template
 */
export const useDeleteTemplate = <TError = Error>(
  templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteTemplate>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteTemplateMutationKey(templateId);
  const swrFn = getDeleteTemplateMutationFetcher(templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Assign template to a workspace (circle)
 */
export const assignTemplateToWorkspace = (
    templateId: number,
    assignTemplateToWorkspaceRequest: AssignTemplateToWorkspaceRequest,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/templates/${templateId}/workspaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignTemplateToWorkspaceRequest
    },
    );
  }



export const getAssignTemplateToWorkspaceMutationFetcher = (templateId: number, ) => {
  return (_: Key, { arg }: { arg: AssignTemplateToWorkspaceRequest }) => {
    return assignTemplateToWorkspace(templateId, arg);
  }
}
export const getAssignTemplateToWorkspaceMutationKey = (templateId: number,) => [`/api/v1/templates/${templateId}/workspaces`] as const;

export type AssignTemplateToWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof assignTemplateToWorkspace>>>
export type AssignTemplateToWorkspaceMutationError = ErrorResponseResponse

/**
 * @summary Assign template to a workspace (circle)
 */
export const useAssignTemplateToWorkspace = <TError = ErrorResponseResponse>(
  templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof assignTemplateToWorkspace>>, TError, Key, AssignTemplateToWorkspaceRequest, Awaited<ReturnType<typeof assignTemplateToWorkspace>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAssignTemplateToWorkspaceMutationKey(templateId);
  const swrFn = getAssignTemplateToWorkspaceMutationFetcher(templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Remove template from a workspace (circle)
 */
export const unassignTemplateFromWorkspace = (
    templateId: number,
    workspaceId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/templates/${templateId}/workspaces/${workspaceId}`, method: 'DELETE'
    },
    );
  }



export const getUnassignTemplateFromWorkspaceMutationFetcher = (templateId: number,
    workspaceId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return unassignTemplateFromWorkspace(templateId, workspaceId);
  }
}
export const getUnassignTemplateFromWorkspaceMutationKey = (templateId: number,
    workspaceId: number,) => [`/api/v1/templates/${templateId}/workspaces/${workspaceId}`] as const;

export type UnassignTemplateFromWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof unassignTemplateFromWorkspace>>>
export type UnassignTemplateFromWorkspaceMutationError = ErrorResponseResponse

/**
 * @summary Remove template from a workspace (circle)
 */
export const useUnassignTemplateFromWorkspace = <TError = ErrorResponseResponse>(
  templateId: number,
    workspaceId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof unassignTemplateFromWorkspace>>, TError, Key, Arguments, Awaited<ReturnType<typeof unassignTemplateFromWorkspace>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUnassignTemplateFromWorkspaceMutationKey(templateId,workspaceId);
  const swrFn = getUnassignTemplateFromWorkspaceMutationFetcher(templateId,workspaceId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Apply template to checklist (creates one checklist item with rows)
 */
export const applyTemplate = (
    checklistId: number,
    templateId: number,
 ) => {
    return customInstance<ChecklistItemResponse>(
    {url: `/api/v1/checklists/${checklistId}/apply-template/${templateId}`, method: 'POST'
    },
    );
  }



export const getApplyTemplateMutationFetcher = (checklistId: number,
    templateId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return applyTemplate(checklistId, templateId);
  }
}
export const getApplyTemplateMutationKey = (checklistId: number,
    templateId: number,) => [`/api/v1/checklists/${checklistId}/apply-template/${templateId}`] as const;

export type ApplyTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof applyTemplate>>>
export type ApplyTemplateMutationError = Error

/**
 * @summary Apply template to checklist (creates one checklist item with rows)
 */
export const useApplyTemplate = <TError = Error>(
  checklistId: number,
    templateId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof applyTemplate>>, TError, Key, Arguments, Awaited<ReturnType<typeof applyTemplate>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getApplyTemplateMutationKey(checklistId,templateId);
  const swrFn = getApplyTemplateMutationFetcher(checklistId,templateId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
