/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ChecklistWithStats,
  CreateInviteRequest,
  CreateWorkspaceRequest,
  ErrorResponseResponse,
  TemplateResponse,
  WorkspaceInviteResponse,
  WorkspaceMemberResponse,
  WorkspaceResponse
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';


  
  
  
/**
 * @summary Get all workspaces for current user
 */
export const getAllWorkspaces = (
    
 ) => {
    return customInstance<WorkspaceResponse[]>(
    {url: `/api/v1/workspaces`, method: 'GET'
    },
    );
  }



export const getGetAllWorkspacesKey = () => [`/api/v1/workspaces`] as const;

export type GetAllWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWorkspaces>>>
export type GetAllWorkspacesQueryError = ErrorResponseResponse

/**
 * @summary Get all workspaces for current user
 */
export const useGetAllWorkspaces = <TError = ErrorResponseResponse>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllWorkspaces>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllWorkspacesKey() : null);
  const swrFn = () => getAllWorkspaces()

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a new workspace
 */
export const createWorkspace = (
    createWorkspaceRequest: CreateWorkspaceRequest,
 ) => {
    return customInstance<WorkspaceResponse>(
    {url: `/api/v1/workspaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkspaceRequest
    },
    );
  }



export const getCreateWorkspaceMutationFetcher = ( ) => {
  return (_: Key, { arg }: { arg: CreateWorkspaceRequest }) => {
    return createWorkspace(arg);
  }
}
export const getCreateWorkspaceMutationKey = () => [`/api/v1/workspaces`] as const;

export type CreateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspace>>>
export type CreateWorkspaceMutationError = ErrorResponseResponse

/**
 * @summary Create a new workspace
 */
export const useCreateWorkspace = <TError = ErrorResponseResponse>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createWorkspace>>, TError, Key, CreateWorkspaceRequest, Awaited<ReturnType<typeof createWorkspace>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateWorkspaceMutationKey();
  const swrFn = getCreateWorkspaceMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get workspace by ID
 */
export const getWorkspaceById = (
    workspaceId: number,
 ) => {
    return customInstance<WorkspaceResponse>(
    {url: `/api/v1/workspaces/${workspaceId}`, method: 'GET'
    },
    );
  }



export const getGetWorkspaceByIdKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}`] as const;

export type GetWorkspaceByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceById>>>
export type GetWorkspaceByIdQueryError = ErrorResponseResponse

/**
 * @summary Get workspace by ID
 */
export const useGetWorkspaceById = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWorkspaceById>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(workspaceId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWorkspaceByIdKey(workspaceId) : null);
  const swrFn = () => getWorkspaceById(workspaceId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update workspace
 */
export const updateWorkspace = (
    workspaceId: number,
    createWorkspaceRequest: CreateWorkspaceRequest,
 ) => {
    return customInstance<WorkspaceResponse>(
    {url: `/api/v1/workspaces/${workspaceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createWorkspaceRequest
    },
    );
  }



export const getUpdateWorkspaceMutationFetcher = (workspaceId: number, ) => {
  return (_: Key, { arg }: { arg: CreateWorkspaceRequest }) => {
    return updateWorkspace(workspaceId, arg);
  }
}
export const getUpdateWorkspaceMutationKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}`] as const;

export type UpdateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkspace>>>
export type UpdateWorkspaceMutationError = ErrorResponseResponse

/**
 * @summary Update workspace
 */
export const useUpdateWorkspace = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateWorkspace>>, TError, Key, CreateWorkspaceRequest, Awaited<ReturnType<typeof updateWorkspace>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateWorkspaceMutationKey(workspaceId);
  const swrFn = getUpdateWorkspaceMutationFetcher(workspaceId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete workspace
 */
export const deleteWorkspace = (
    workspaceId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/workspaces/${workspaceId}`, method: 'DELETE'
    },
    );
  }



export const getDeleteWorkspaceMutationFetcher = (workspaceId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteWorkspace(workspaceId);
  }
}
export const getDeleteWorkspaceMutationKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}`] as const;

export type DeleteWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspace>>>
export type DeleteWorkspaceMutationError = ErrorResponseResponse

/**
 * @summary Delete workspace
 */
export const useDeleteWorkspace = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteWorkspace>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteWorkspace>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteWorkspaceMutationKey(workspaceId);
  const swrFn = getDeleteWorkspaceMutationFetcher(workspaceId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get workspace members
 */
export const getWorkspaceMembers = (
    workspaceId: number,
 ) => {
    return customInstance<WorkspaceMemberResponse[]>(
    {url: `/api/v1/workspaces/${workspaceId}/members`, method: 'GET'
    },
    );
  }



export const getGetWorkspaceMembersKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}/members`] as const;

export type GetWorkspaceMembersQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceMembers>>>
export type GetWorkspaceMembersQueryError = ErrorResponseResponse

/**
 * @summary Get workspace members
 */
export const useGetWorkspaceMembers = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWorkspaceMembers>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(workspaceId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWorkspaceMembersKey(workspaceId) : null);
  const swrFn = () => getWorkspaceMembers(workspaceId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Remove a member from workspace
 */
export const removeWorkspaceMember = (
    workspaceId: number,
    memberId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/workspaces/${workspaceId}/members/${memberId}`, method: 'DELETE'
    },
    );
  }



export const getRemoveWorkspaceMemberMutationFetcher = (workspaceId: number,
    memberId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return removeWorkspaceMember(workspaceId, memberId);
  }
}
export const getRemoveWorkspaceMemberMutationKey = (workspaceId: number,
    memberId: number,) => [`/api/v1/workspaces/${workspaceId}/members/${memberId}`] as const;

export type RemoveWorkspaceMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeWorkspaceMember>>>
export type RemoveWorkspaceMemberMutationError = ErrorResponseResponse

/**
 * @summary Remove a member from workspace
 */
export const useRemoveWorkspaceMember = <TError = ErrorResponseResponse>(
  workspaceId: number,
    memberId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof removeWorkspaceMember>>, TError, Key, Arguments, Awaited<ReturnType<typeof removeWorkspaceMember>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRemoveWorkspaceMemberMutationKey(workspaceId,memberId);
  const swrFn = getRemoveWorkspaceMemberMutationFetcher(workspaceId,memberId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Leave a workspace
 */
export const leaveWorkspace = (
    workspaceId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/workspaces/${workspaceId}/leave`, method: 'POST'
    },
    );
  }



export const getLeaveWorkspaceMutationFetcher = (workspaceId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return leaveWorkspace(workspaceId);
  }
}
export const getLeaveWorkspaceMutationKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}/leave`] as const;

export type LeaveWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof leaveWorkspace>>>
export type LeaveWorkspaceMutationError = ErrorResponseResponse

/**
 * @summary Leave a workspace
 */
export const useLeaveWorkspace = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof leaveWorkspace>>, TError, Key, Arguments, Awaited<ReturnType<typeof leaveWorkspace>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getLeaveWorkspaceMutationKey(workspaceId);
  const swrFn = getLeaveWorkspaceMutationFetcher(workspaceId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary List active invite links for a workspace
 */
export const getWorkspaceInvites = (
    workspaceId: number,
 ) => {
    return customInstance<WorkspaceInviteResponse[]>(
    {url: `/api/v1/workspaces/${workspaceId}/invites`, method: 'GET'
    },
    );
  }



export const getGetWorkspaceInvitesKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}/invites`] as const;

export type GetWorkspaceInvitesQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceInvites>>>
export type GetWorkspaceInvitesQueryError = ErrorResponseResponse

/**
 * @summary List active invite links for a workspace
 */
export const useGetWorkspaceInvites = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWorkspaceInvites>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(workspaceId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWorkspaceInvitesKey(workspaceId) : null);
  const swrFn = () => getWorkspaceInvites(workspaceId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a new workspace invite link
 */
export const createWorkspaceInvite = (
    workspaceId: number,
    createInviteRequest: CreateInviteRequest,
 ) => {
    return customInstance<WorkspaceInviteResponse>(
    {url: `/api/v1/workspaces/${workspaceId}/invites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInviteRequest
    },
    );
  }



export const getCreateWorkspaceInviteMutationFetcher = (workspaceId: number, ) => {
  return (_: Key, { arg }: { arg: CreateInviteRequest }) => {
    return createWorkspaceInvite(workspaceId, arg);
  }
}
export const getCreateWorkspaceInviteMutationKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}/invites`] as const;

export type CreateWorkspaceInviteMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspaceInvite>>>
export type CreateWorkspaceInviteMutationError = ErrorResponseResponse

/**
 * @summary Create a new workspace invite link
 */
export const useCreateWorkspaceInvite = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createWorkspaceInvite>>, TError, Key, CreateInviteRequest, Awaited<ReturnType<typeof createWorkspaceInvite>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateWorkspaceInviteMutationKey(workspaceId);
  const swrFn = getCreateWorkspaceInviteMutationFetcher(workspaceId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Revoke a workspace invite link
 */
export const revokeWorkspaceInvite = (
    workspaceId: number,
    inviteId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/workspaces/${workspaceId}/invites/${inviteId}`, method: 'DELETE'
    },
    );
  }



export const getRevokeWorkspaceInviteMutationFetcher = (workspaceId: number,
    inviteId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return revokeWorkspaceInvite(workspaceId, inviteId);
  }
}
export const getRevokeWorkspaceInviteMutationKey = (workspaceId: number,
    inviteId: number,) => [`/api/v1/workspaces/${workspaceId}/invites/${inviteId}`] as const;

export type RevokeWorkspaceInviteMutationResult = NonNullable<Awaited<ReturnType<typeof revokeWorkspaceInvite>>>
export type RevokeWorkspaceInviteMutationError = ErrorResponseResponse

/**
 * @summary Revoke a workspace invite link
 */
export const useRevokeWorkspaceInvite = <TError = ErrorResponseResponse>(
  workspaceId: number,
    inviteId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof revokeWorkspaceInvite>>, TError, Key, Arguments, Awaited<ReturnType<typeof revokeWorkspaceInvite>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getRevokeWorkspaceInviteMutationKey(workspaceId,inviteId);
  const swrFn = getRevokeWorkspaceInviteMutationFetcher(workspaceId,inviteId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get templates in a workspace
 */
export const getWorkspaceTemplates = (
    workspaceId: number,
 ) => {
    return customInstance<TemplateResponse[]>(
    {url: `/api/v1/workspaces/${workspaceId}/templates`, method: 'GET'
    },
    );
  }



export const getGetWorkspaceTemplatesKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}/templates`] as const;

export type GetWorkspaceTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceTemplates>>>
export type GetWorkspaceTemplatesQueryError = ErrorResponseResponse

/**
 * @summary Get templates in a workspace
 */
export const useGetWorkspaceTemplates = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWorkspaceTemplates>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(workspaceId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWorkspaceTemplatesKey(workspaceId) : null);
  const swrFn = () => getWorkspaceTemplates(workspaceId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get checklists in a workspace
 */
export const getWorkspaceChecklists = (
    workspaceId: number,
 ) => {
    return customInstance<ChecklistWithStats[]>(
    {url: `/api/v1/workspaces/${workspaceId}/checklists`, method: 'GET'
    },
    );
  }



export const getGetWorkspaceChecklistsKey = (workspaceId: number,) => [`/api/v1/workspaces/${workspaceId}/checklists`] as const;

export type GetWorkspaceChecklistsQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceChecklists>>>
export type GetWorkspaceChecklistsQueryError = ErrorResponseResponse

/**
 * @summary Get checklists in a workspace
 */
export const useGetWorkspaceChecklists = <TError = ErrorResponseResponse>(
  workspaceId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWorkspaceChecklists>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(workspaceId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWorkspaceChecklistsKey(workspaceId) : null);
  const swrFn = () => getWorkspaceChecklists(workspaceId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
