/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Checklist service v1
 * Checklist service v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateRecipeRequest,
  UpdateRecipeRequest,
  RecipeResponse,
  Error
} from '../checklistServiceV1.schemas';

import { customInstance } from '../../lib/axios';





/**
 * @summary Get all recipes for the authenticated user
 */
export const getAllRecipes = (

 ) => {
    return customInstance<RecipeResponse[]>(
    {url: `/api/v1/recipes`, method: 'GET'
    },
    );
  }



export const getGetAllRecipesKey = () => [`/api/v1/recipes`] as const;

export type GetAllRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRecipes>>>
export type GetAllRecipesQueryError = Error

/**
 * @summary Get all recipes for the authenticated user
 */
export const useGetAllRecipes = <TError = Error>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllRecipes>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllRecipesKey() : null);
  const swrFn = () => getAllRecipes()

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create a new recipe
 */
export const createRecipe = (
    createRecipeRequest: CreateRecipeRequest,
 ) => {
    return customInstance<RecipeResponse>(
    {url: `/api/v1/recipes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRecipeRequest
    },
    );
  }



export const getCreateRecipeMutationFetcher = ( ) => {
  return (_: Key, { arg }: { arg: CreateRecipeRequest }) => {
    return createRecipe(arg);
  }
}
export const getCreateRecipeMutationKey = () => [`/api/v1/recipes`] as const;

export type CreateRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof createRecipe>>>
export type CreateRecipeMutationError = Error | Error

/**
 * @summary Create a new recipe
 */
export const useCreateRecipe = <TError = Error | Error>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createRecipe>>, TError, Key, CreateRecipeRequest, Awaited<ReturnType<typeof createRecipe>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateRecipeMutationKey();
  const swrFn = getCreateRecipeMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get recipe by ID
 */
export const getRecipeById = (
    recipeId: number,
 ) => {
    return customInstance<RecipeResponse>(
    {url: `/api/v1/recipes/${recipeId}`, method: 'GET'
    },
    );
  }



export const getGetRecipeByIdKey = (recipeId: number,) => [`/api/v1/recipes/${recipeId}`] as const;

export type GetRecipeByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getRecipeById>>>
export type GetRecipeByIdQueryError = Error | Error

/**
 * @summary Get recipe by ID
 */
export const useGetRecipeById = <TError = Error | Error>(
  recipeId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getRecipeById>>, TError> & { swrKey?: Key, enabled?: boolean },  }
) => {
  const {swr: swrOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(recipeId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetRecipeByIdKey(recipeId) : null);
  const swrFn = () => getRecipeById(recipeId)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update recipe by ID (full replace)
 */
export const updateRecipeById = (
    recipeId: number,
    updateRecipeRequest: UpdateRecipeRequest,
 ) => {
    return customInstance<RecipeResponse>(
    {url: `/api/v1/recipes/${recipeId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRecipeRequest
    },
    );
  }



export const getUpdateRecipeByIdMutationFetcher = (recipeId: number, ) => {
  return (_: Key, { arg }: { arg: UpdateRecipeRequest }) => {
    return updateRecipeById(recipeId, arg);
  }
}
export const getUpdateRecipeByIdMutationKey = (recipeId: number,) => [`/api/v1/recipes/${recipeId}`] as const;

export type UpdateRecipeByIdMutationResult = NonNullable<Awaited<ReturnType<typeof updateRecipeById>>>
export type UpdateRecipeByIdMutationError = Error | Error | Error

/**
 * @summary Update recipe by ID (full replace)
 */
export const useUpdateRecipeById = <TError = Error | Error | Error>(
  recipeId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateRecipeById>>, TError, Key, UpdateRecipeRequest, Awaited<ReturnType<typeof updateRecipeById>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateRecipeByIdMutationKey(recipeId);
  const swrFn = getUpdateRecipeByIdMutationFetcher(recipeId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Delete recipe by ID
 */
export const deleteRecipeById = (
    recipeId: number,
 ) => {
    return customInstance<void>(
    {url: `/api/v1/recipes/${recipeId}`, method: 'DELETE'
    },
    );
  }



export const getDeleteRecipeByIdMutationFetcher = (recipeId: number, ) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteRecipeById(recipeId);
  }
}
export const getDeleteRecipeByIdMutationKey = (recipeId: number,) => [`/api/v1/recipes/${recipeId}`] as const;

export type DeleteRecipeByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRecipeById>>>
export type DeleteRecipeByIdMutationError = Error | Error

/**
 * @summary Delete recipe by ID
 */
export const useDeleteRecipeById = <TError = Error | Error>(
  recipeId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteRecipeById>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteRecipeById>>> & { swrKey?: string }, }
) => {

  const {swr: swrOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteRecipeByIdMutationKey(recipeId);
  const swrFn = getDeleteRecipeByIdMutationFetcher(recipeId);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
